import type { IdeaDrop } from "@/types/idea-drop";

/**
 * Compiles an IdeaDrop into a ready-to-use .cursorrules configuration file
 * for Cursor and Windsurf editors.
 */
export function generateCursorRules(idea: IdeaDrop): string {
  const stackSummary = idea.launchStack
    .map((s) => `- ${s.layer}: ${s.tool} (${s.freeTierNote})`)
    .join("\n");

  const coreLoop = idea.buildBrief.coreLoop
    .map((step, i) => `${i + 1}. ${step}`)
    .join("\n");

  const mvpScope = idea.buildBrief.mvpScope
    .map((item) => `- [x] ${item}`)
    .join("\n");

  const explicitlyCut = idea.buildBrief.explicitlyCut
    .map((item) => `- [ ] PROHIBITED IN MVP: ${item}`)
    .join("\n");

  const entities = idea.buildBrief.dataModel
    .map((e) => `- ${e.name}: ${e.fields}`)
    .join("\n");

  const apis = idea.matchedApis
    .map((api) => `- ${api.name}: ${api.purpose} (Free tier: ${api.freeTierLimit}) -> ${api.sourceUrl}`)
    .join("\n");

  return `# .cursorrules — ${idea.title}
# Generated by Sourced (https://www.getsourced.dev/feed/${idea.slug})
# Role: Senior Full-Stack Autonomous Engineer

You are building "${idea.title}".
Your mandate is to implement a lean, functional MVP that directly solves this real-world complaint without scope creep.

## Problem Context
- Problem: ${idea.problem.summary}
- Target User: ${idea.problem.whoFeelsIt}
- Why Now: ${idea.whyNow}

## Approved Technology Stack
${stackSummary}

## The Core Product Loop
${coreLoop}

## MVP Scope (Build ONLY These Features)
${mvpScope}

## Explicitly Cut Features (DO NOT BUILD)
Refuse to build or scaffold these features. If the user asks for them, remind them they were cut to protect launch velocity:
${explicitlyCut}

## Data Models
${entities}

## External APIs & Integrations
${apis}

## Engineering & Coding Standards
1. **TypeScript & Type Safety**: Strict typing everywhere. No \`any\` or unvalidated type assertions. Use Zod for runtime schema boundaries.
2. **Resilience**: Every external API call must have explicit timeout handling (\`AbortSignal.timeout\`) and exponential backoff retry.
3. **Database Security**: Always apply Row Level Security (RLS) policies for user data isolation.
4. **UI Design**: Space Grotesk / JetBrains Mono typography, clean accessible card/chip interface, responsive layout, smooth state transitions.
5. **No Hallucinations**: Never invent API endpoints or credentials not listed above.

## Kickoff Prompt
${idea.agentPrompts.cursorWindsurf}
`;
}
