import type { IdeaDrop } from "@/types/idea-drop";

export function generateProductionContract(idea: IdeaDrop): string {
  const shortSlug = idea.slug;
  const coreEntities = idea.buildBrief.dataModel;

  // Generate SQL DDL for entities
  const sqlTables = coreEntities.map((entity) => {
    const tableName = entity.name.toLowerCase().replace(/[^a-z0-9_]/g, "_") + "s";
    const rawFields = entity.fields.split(",").map((f) => f.trim()).filter(Boolean);
    const columns = rawFields.map((field) => {
      const lower = field.toLowerCase();
      if (lower === "id") return "  id uuid primary key default gen_random_uuid()";
      if (lower.includes("created_at") || lower.includes("updated_at") || lower.includes("date")) {
        return `  ${lower} timestamptz not null default now()`;
      }
      if (lower.includes("amount") || lower.includes("price") || lower.includes("cost")) {
        return `  ${lower} numeric(12, 2) not null default 0.00`;
      }
      if (lower.includes("is_") || lower.includes("has_") || lower.includes("active")) {
        return `  ${lower} boolean not null default false`;
      }
      if (lower.includes("count") || lower.includes("total") || lower.includes("score")) {
        return `  ${lower} integer not null default 0`;
      }
      if (lower.includes("metadata") || lower.includes("settings") || lower.includes("data")) {
        return `  ${lower} jsonb not null default '{}'::jsonb`;
      }
      return `  ${lower} text not null`;
    });

    // Ensure id and created_at exist
    if (!columns.some((c) => c.includes("id uuid primary key"))) {
      columns.unshift("  id uuid primary key default gen_random_uuid()");
    }
    if (!columns.some((c) => c.includes("created_at"))) {
      columns.push("  created_at timestamptz not null default now()");
    }
    if (!columns.some((c) => c.includes("updated_at"))) {
      columns.push("  updated_at timestamptz not null default now()");
    }

    return `-- Table: ${tableName}\ncreate table if not exists public.${tableName} (\n${columns.join(",\n")}\n);\n\nalter table public.${tableName} enable row level security;\n\ncreate policy "${tableName}_user_isolation" on public.${tableName}\n  for all using (auth.uid() is not null);`;
  }).join("\n\n");

  const apisSection = idea.matchedApis.map((api) => {
    return `- **${api.name}**: ${api.purpose}\n  - Free tier budget: ${api.freeTierLimit}\n  - Reference: ${api.sourceUrl}\n  - Implementation rule: Wrap in retry logic with exponential backoff (max 3 retries).`;
  }).join("\n");

  const coreLoopSection = idea.buildBrief.coreLoop.map((step, i) => `${i + 1}. ${step}`).join("\n");
  const inScopeSection = idea.buildBrief.mvpScope.map((item) => `- [x] ${item}`).join("\n");
  const cutSection = idea.buildBrief.explicitlyCut.map((item) => `- [ ] DO NOT BUILD: ${item} (cut to protect launch speed)`).join("\n");

  return `# Production Architecture Specification: ${idea.title}

> Generated by Sourced (https://www.getsourced.dev/feed/${idea.slug})
> Evidence-backed build brief triangulated across real developer complaints.

## 1. Project Mission & Problem Statement

- **Target Persona**: ${idea.problem.whoFeelsIt}
- **Core Problem**: ${idea.problem.summary}
- **Why Now**: ${idea.whyNow}

---

## 2. Agent Execution Rules (Claude Code / Cursor / Windsurf)

1. **Spec-Driven Development**: Treat this file as the iron contract. Do not hallucinate features not in MVP scope.
2. **Type Safety**: Full TypeScript strict mode. Zero \`any\` types permitted.
3. **Architecture**: Next.js App Router, Supabase (Postgres + Auth + Storage), Vitest for unit testing.
4. **Security & RLS**: All database queries must enforce tenant isolation via Supabase RLS. Never use service role keys in client components.
5. **Preserve Cut Scope**: Respect the "Explicitly Cut" section to deliver a hardened, launch-ready MVP within 48 hours.

---

## 3. Database Schema (PostgreSQL / Supabase DDL)

\`\`\`sql
${sqlTables}
\`\`\`

---

## 4. Core Implementation Loop

${coreLoopSection}

### MVP Scope (IN)
${inScopeSection}

### Scope Boundaries (OUT)
${cutSection}

---

## 5. Third-Party APIs & Integration Contracts

${apisSection}

---

## 6. Edge Cases & Production Failure Modes

- **Network & Rate Limits**: Gracefully handle 429 status codes from third-party APIs by queuing requests with local backoff.
- **Data Ingestion Failures**: Validate file uploads (CSV, JSON, PDFs) against strict Zod schemas before processing.
- **Idempotency**: Prevent duplicate transaction or webhook processing by checking unique idempotency keys in Redis or Supabase.
- **Zero-State Experience**: Display clear empty states with sample data so new users understand the value instantly.

---

## 7. Verification & Acceptance Criteria

Run the following test suite before declaring the MVP complete:

\`\`\`bash
# 1. Typecheck
npm run typecheck

# 2. Unit & Integration Tests
npm test

# 3. Production Build
npm run build
\`\`\`
`;
}
